### ISSUE TITLE
CICS plugin fails when not using profile and targeting a specific CICS region

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli-cics-plugin#14]
With no CICS profile set:
```
C:\Users\user>set ZOWE_OPT_USER=user

C:\Users\user>set ZOWE_OPT_PASSWORD=myPass

C:\Users\user>set ZOWE_OPT_HOST=myHost

C:\Users\user>set ZOWE_OPT_PORT=1490

C:\Users\user>bright cics get resource CICSLocalTransaction -c "PROGRAM=MARB*" --rft table --rfh --rff program tranid status --region-name RGN1
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\get\resource/Resource.handler"
Message:
Cannot read property 'cicsPlex' of undefined
Stack:
TypeError: Cannot read property 'cicsPlex' of undefined
    at ResourceHandler.<anonymous> (C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\get\resource\Resource.handler.js:44:64)
    at Generator.next (<anonymous>)
    at C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\get\resource\Resource.handler.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\get\resource\Resource.handler.js:13:12)
    at ResourceHandler.processWithSession (C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\get\resource\Resource.handler.js:34:16)
    at ResourceHandler.<anonymous> (C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\CicsBaseHandler.js:39:41)
    at Generator.next (<anonymous>)
    at C:\Users\user\.zowe\plugins\installed\node_modules\@brightside\cics\lib\cli\CicsBaseHandler.js:17:71
    at new Promise (<anonymous>)
```

zowe cli version: 2.0.0-next.201811292055
zowe cics plugin version: 1.1.0-next.201812131943

node version: v8.11.3
npm version: 6.4.1

**Comment by AHumanFromCA** [comment]
Hi @MikeBauerCA,

Thanks for catching this one, I talked this one over with @zFernand0 and we think this is due to the recent change to allow command option precedence in the plugin.

Originally, this was coded in manually for the CICS profile options and the command was meant to handle the cases where options were set as blank. When we moved it to the new scheme I don't think we entirely removed this dependency.

I believe the problem comes from this function in the handler:

https://github.com/zowe/zowe-cli-cics-plugin/blob/d658f6f4f2ad8019db6fff14ce0b305d7f58e439/src/cli/get/resource/Resource.handler.ts#L28-L51

If no profile has been previously set, I believe that the profile coming into the function will be null, triggering the null reference of profile.cicsPlex.

**Comment by AHumanFromCA** [comment]
I think this could be addressed by changing this line:

https://github.com/zowe/zowe-cli-cics-plugin/blob/d658f6f4f2ad8019db6fff14ce0b305d7f58e439/src/cli/CicsBaseHandler.ts#L30

to

```TypeScript
const profile = commandParameters.profiles.get("cics", false) || {};
```

**Comment by MikeBauerCA** [comment]
I can confirm that making that suggested code change resolves the issue. Thanks!
